### ISSUE TITLE
Kleidung ausziehen

### ISSUE THREAD

**Issue by BlackRiderNU** [NewU-RP/NewU-RP#23]
**Describe the bug**
Kleidung ausziehen funktioniert seit dem neuen AltV-Update nicht mehr.

**Comment by BlackRiderNU** [comment]
Geändert in Feature Request - wurde nie vollständig implementiert.

**Comment by BlackRiderNU** [comment]
Implementiert, muss noch getestet werden.

**Comment by speeed2011** [comment]
Ablegen ansich funktioniert nun, allerdings verschwinden die Klamotten nicht am Char. Weg werfen geht auch.
Hüte kann man noch nicht ablegen.

**Comment by BlackRiderNU** [comment]
Fixed.

> Ablegen ansich funktioniert nun, allerdings verschwinden die Klamotten nicht am Char. Weg werfen geht auch. Hüte kann man noch nicht ablegen.

Lässt sich bei dir nicht ablegen, da du ihn falsch gespawnt hast. Müsstest dir einen neuen Hut spawnen und den nutzen, dann sollte es funktionieren.

**Comment by BlackRiderNU** [comment]
Korrektur - Hüte lassen sich auch so nicht ablegen :D

**Comment by BlackRiderNU** [comment]
Fixed.
